BOOLEAN_LOGIC = [
    # <BOOLEAN_LOGIC> = LOGICAL_NOT | LOGICAL_OR | LOGICAL_AND
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_NOT><WHITESPACE><DT_INT><IDENTIFIER>",
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_OR><WHITESPACE><DT_INT><IDENTIFIER>",
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_AND><WHITESPACE><DT_INT><IDENTIFIER>",

    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_NOT><WHITESPACE><DT_DECI><IDENTIFIER>",
    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_OR><WHITESPACE><DT_DECI><IDENTIFIER>",
    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_AND><WHITESPACE><DT_DECI><IDENTIFIER>",

    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_NOT><WHITESPACE><DT_CHAR><IDENTIFIER>",
    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_OR><WHITESPACE><DT_CHAR><IDENTIFIER>",
    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_AND><WHITESPACE><DT_CHAR><IDENTIFIER>",

    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_NOT><WHITESPACE><DT_STR><IDENTIFIER>",
    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_OR><WHITESPACE><DT_STR><IDENTIFIER>",
    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_AND><WHITESPACE><DT_STR><IDENTIFIER>",

    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_NOT><WHITESPACE><DT_BOOL><IDENTIFIER>",
    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_OR><WHITESPACE><DT_BOOL><IDENTIFIER>",
    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_AND><WHITESPACE><DT_BOOL><IDENTIFIER>",

    # "<DATA_TYPE><WHITESPACE><IDENTIFIER><WHITESPACE><BOOLEAN_LOGIC><WHITESPACE><VALUE>"
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_NOT><WHITESPACE><INTEGER>",
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_OR><WHITESPACE><INTEGER>",
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_AND><WHITESPACE><INTEGER>",

    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_NOT><WHITESPACE><DECIMAL>",
    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_OR><WHITESPACE><DECIMAL>",
    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_AND><WHITESPACE><DECIMAL>",

    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_NOT><WHITESPACE><STRING>",  # -------------------------
    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_OR><WHITESPACE><STRING>",  # -------------------------
    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_AND><WHITESPACE><STRING>",  # -------------------------

    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_NOT><WHITESPACE><STRING>",
    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_OR><WHITESPACE><STRING>",
    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_AND><WHITESPACE><STRING>",

    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_NOT><WHITESPACE><BOOL_VALUE>",
    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_OR><WHITESPACE><BOOL_VALUE>",
    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_AND><WHITESPACE><BOOL_VALUE>"

]

BOOLEAN_RELATION = [  # dapat same ng data type, rules q yan
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL_TO><WHITESPACE><DT_INT><WHITESPACE><IDENTIFIER>",
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><NOT_EQUAL><WHITESPACE><DT_INT><WHITESPACE><IDENTIFIER>",
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><GREATER_THAN><WHITESPACE><DT_INT><WHITESPACE><IDENTIFIER>",
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><LESS_THAN><WHITESPACE><DT_INT><WHITESPACE><IDENTIFIER>",
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><DT_INT><WHITESPACE><IDENTIFIER>",
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><DT_INT><WHITESPACE><IDENTIFIER>",

    # e.g. deci x >= deci y
    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL_TO><WHITESPACE><DT_DECI><WHITESPACE><IDENTIFIER>",
    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><NOT_EQUAL><WHITESPACE><DT_DECI><WHITESPACE><IDENTIFIER>",
    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><GREATER_THAN><WHITESPACE><DT_DECI><WHITESPACE><IDENTIFIER>",
    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><LESS_THAN><WHITESPACE><DT_DECI><WHITESPACE><IDENTIFIER>",
    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><DT_DECI><WHITESPACE><IDENTIFIER>",
    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><DT_DECI><WHITESPACE><IDENTIFIER>",

    # e.g. str x <= str x
    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL_TO><WHITESPACE><DT_STR><WHITESPACE><IDENTIFIER>",
    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><NOT_EQUAL><WHITESPACE><DT_STR><WHITESPACE><IDENTIFIER>",
    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><GREATER_THAN><WHITESPACE><DT_STR><WHITESPACE><IDENTIFIER>",
    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><LESS_THAN><WHITESPACE><DT_STR><WHITESPACE><IDENTIFIER>",
    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><DT_STR><WHITESPACE><IDENTIFIER>",
    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><DT_STR><WHITESPACE><IDENTIFIER>",

    # e.g. char x <= char x
    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL_TO><WHITESPACE><DT_CHAR><WHITESPACE><IDENTIFIER>",
    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><NOT_EQUAL><WHITESPACE><DT_CHAR><WHITESPACE><IDENTIFIER>",
    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><GREATER_THAN><WHITESPACE><DT_CHAR><WHITESPACE><IDENTIFIER>",
    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><LESS_THAN><WHITESPACE><DT_CHAR><WHITESPACE><IDENTIFIER>",
    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><DT_CHAR><WHITESPACE><IDENTIFIER>",
    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><DT_CHAR><WHITESPACE><IDENTIFIER>",

    # e.g. bool x <= bool x
    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL_TO><WHITESPACE><DT_BOOL><WHITESPACE><IDENTIFIER>",
    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><NOT_EQUAL><WHITESPACE><DT_BOOL><WHITESPACE><IDENTIFIER>",
    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><GREATER_THAN><WHITESPACE><DT_BOOL><WHITESPACE><IDENTIFIER>",
    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><LESS_THAN><WHITESPACE><DT_BOOL><WHITESPACE><IDENTIFIER>",
    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><DT_BOOL><WHITESPACE><IDENTIFIER>",
    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><DT_BOOL><WHITESPACE><IDENTIFIER>",

    # e.g. x <= y
    "<IDENTIFIER><WHITESPACE><EQUAL_TO><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><WHITESPACE><NOT_EQUAL><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><WHITESPACE><GREATER_THAN><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><WHITESPACE><LESS_THAN><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><IDENTIFIER>",

    # 12 >= 13
    "<INTEGER><WHITESPACE><EQUAL_TO><WHITESPACE><INTEGER>",
    "<INTEGER><WHITESPACE><NOT_EQUAL><WHITESPACE><INTEGER>",
    "<INTEGER><WHITESPACE><GREATER_THAN><WHITESPACE><INTEGER>",
    "<INTEGER><WHITESPACE><LESS_THAN><WHITESPACE><INTEGER>",
    "<INTEGER><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><INTEGER>",
    "<INTEGER><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><INTEGER>",

    # 12.312 <= 12.231
    "<DECIMAL><WHITESPACE><EQUAL_TO><WHITESPACE><DECIMAL>",
    "<DECIMAL><WHITESPACE><NOT_EQUAL><WHITESPACE><DECIMAL>",
    "<DECIMAL><WHITESPACE><GREATER_THAN><WHITESPACE><DECIMAL>",
    "<DECIMAL><WHITESPACE><LESS_THAN><WHITESPACE><DECIMAL>",
    "<DECIMAL><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><DECIMAL>",
    "<DECIMAL><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><DECIMAL>",

    # TRUE == FALSE
    "<BOOL_VALUE><WHITESPACE><EQUAL_TO><WHITESPACE><BOOL_VALUE>",
    "<BOOL_VALUE><WHITESPACE><NOT_EQUAL><WHITESPACE><BOOL_VALUE>",
    "<BOOL_VALUE><WHITESPACE><GREATER_THAN><WHITESPACE><BOOL_VALUE>",
    "<BOOL_VALUE><WHITESPACE><LESS_THAN><WHITESPACE><BOOL_VALUE>",
    "<BOOL_VALUE><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><BOOL_VALUE>",
    "<BOOL_VALUE><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><BOOL_VALUE>",

    # "TEST" >= "TASTY"
    "<STRING><WHITESPACE><EQUAL_TO><WHITESPACE><STRING>",
    "<STRING><WHITESPACE><NOT_EQUAL><WHITESPACE><STRING>",
    "<STRING><WHITESPACE><GREATER_THAN><WHITESPACE><STRING>",
    "<STRING><WHITESPACE><LESS_THAN><WHITESPACE><STRING>",
    "<STRING><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><STRING>",
    "<STRING><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><STRING>",

]

for x in BOOLEAN_RELATION:
        for y in BOOLEAN_RELATION:
                BOOLEAN_LOGIC.append(f"{x}<WHITESPACE><LOGICAL_NOT><WHITESPACE>{y}")
                BOOLEAN_LOGIC.append(f"{x}<WHITESPACE><LOGICAL_OR><WHITESPACE>{y}")
                BOOLEAN_LOGIC.append(f"{x}<WHITESPACE><LOGICAL_AND><WHITESPACE>{y}")

