DATA_TYPES = ["<DT_INT>", "<DT_DECI>", "<DT_STR>", "<DT_CHAR>", "<DT_BOOL>"]
DATA_VALUES = ["<INTEGER>", "<DECIMAL>", "<STRING>", "<CHAR>", "<BOOL_VALUE>"]
ARITHMETIC_OPS = ["<PLUS>", "<MINUS>", "<MULTIPLY>", "<DIVIDE>"]
ASSIGNMENT_OPS = ["<ADD_ASS>", "<SUBTRACT_ASS>", "<MULTIPLY_ASS>", "<DIVIDE_ASS>", "<MODULO_ASS>"]

DECLARATION_STMT =  [
    f"{dt}<WHITESPACE><IDENTIFIER>" for dt in DATA_TYPES
]

MULTI_DECLARATION_STMT = []

for num_variables in range(1, 20):
    for line in DECLARATION_STMT:
        token = "<COMMA><WHITESPACE><IDENTIFIER>" * num_variables
        MULTI_DECLARATION_STMT.append(f"{line}{token}")

DECLARATION_STMT = DECLARATION_STMT + MULTI_DECLARATION_STMT

ASSIGNMENT_STMT = [
        "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL><WHITESPACE><IDENTIFIER>",  # int age = x
        "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL><WHITESPACE><IDENTIFIER>",  # deci gpa = y
        "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL><WHITESPACE><IDENTIFIER>",   # str y = z
        "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL><WHITESPACE><IDENTIFIER>", # char z = y
        "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL><WHITESPACE><IDENTIFIER>", # bool s = h
        "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL><WHITESPACE><CONSTANT>", # deci value_pi = pi
]

ASSIGNMENT_OPERATORS = []
for x in range(len(DATA_TYPES)):
    token = f"{DATA_TYPES[x]}<WHITESPACE><IDENTIFIER><WHITESPACE>{ASSIGNMENT_OPS[x]}<WHITESPACE><IDENTIFIER>"
    ASSIGNMENT_OPERATORS.append(token)

ARITHMETIC_EXP = []
for num in range(1, 15):
    for x in range(len(DATA_VALUES)):
        addition = f"{DATA_VALUES[x]}<WHITESPACE><PLUS><WHITESPACE>{DATA_VALUES[x]}" * num
        subtraction = f"{DATA_VALUES[x]}<WHITESPACE><MINUS><WHITESPACE>{DATA_VALUES[x]}" * num
        division = f"{DATA_VALUES[x]}<WHITESPACE><DIVIDE><WHITESPACE>{DATA_VALUES[x]}" * num
        multiplication = f"{DATA_VALUES[x]}<WHITESPACE><MULTIPLY><WHITESPACE>{DATA_VALUES[x]}" * num

        ARITHMETIC_EXP.append(addition)
        ARITHMETIC_EXP.append(subtraction)
        ARITHMETIC_EXP.append(division)
        ARITHMETIC_EXP.append(multiplication)

# int x = 10
ASSIGNMENT_IDENVALUE = []
for i in range(len(DATA_TYPES)):
    ASSIGNMENT_IDENVALUE.append(f"{DATA_TYPES[i]}<WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL><WHITESPACE>{DATA_VALUES[i]}")

MULTI_ASSIGNMENT_IDENVALUE = []
for num in range(1, 15):
    for i in range(len(DATA_TYPES)):
        token = f"<COMMA><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL><WHITESPACE>{DATA_VALUES[i]}" * num
        MULTI_ASSIGNMENT_IDENVALUE.append(f"{ASSIGNMENT_IDENVALUE[i]}{token}")

# int x = 1 + 1

ASSIGNMENT_EXP = []
for num in range(1, 15):
    for value, dt in zip(DATA_VALUES, DATA_TYPES):
        for operator in ARITHMETIC_OPS:
            arithmetic_expression = f"{dt}<WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL><WHITESPACE>{value}<WHITESPACE>{operator}<WHITESPACE>{value}" * num
            ASSIGNMENT_EXP.append(arithmetic_expression)

MULTI_ASSIGNMENT_EXP = []
for num in range(1, 15):
    for i in range(len(DATA_TYPES)):
        token = f"<COMMA><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL><WHITESPACE>{ARITHMETIC_EXP[i]}" * num
        MULTI_ASSIGNMENT_EXP.append(f"{ASSIGNMENT_EXP[i]}{token}")


VALID_ASSIGN = ASSIGNMENT_OPERATORS + ASSIGNMENT_IDENVALUE + MULTI_ASSIGNMENT_IDENVALUE + ASSIGNMENT_EXP + MULTI_ASSIGNMENT_EXP

for x in VALID_ASSIGN:
    ASSIGNMENT_STMT.append(x)

INPUT_STMT = [
        "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL><WHITESPACE><INPUT><PARENTHESIS_OPEN><PARENTHESIS_CLOSE>",
        "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL><WHITESPACE><INPUT><PARENTHESIS_OPEN><PARENTHESIS_CLOSE>",
        "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL><WHITESPACE><INPUT><PARENTHESIS_OPEN><PARENTHESIS_CLOSE>",
]

OUTPUT_STMT = [
        # e.g. output("hello")
        "<OUTPUT><PARENTHESIS_OPEN><STRING><PARENTHESIS_CLOSE>",
        "<OUTPUT><PARENTHESIS_OPEN><IDENTIFIER><PARENTHESIS_CLOSE>",
        "<OUTPUT><PARENTHESIS_OPEN><STRING><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE>",

        "<OUTPUT><PARENTHESIS_OPEN><STRING><PARENTHESIS_CLOSE><WHITESPACE>",
        "<OUTPUT><PARENTHESIS_OPEN><IDENTIFIER><PARENTHESIS_CLOSE><WHITESPACE>",
        "<OUTPUT><PARENTHESIS_OPEN><STRING><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE><WHITESPACE>",
               
        "<OUTPUT><PARENTHESIS_OPEN><STRING><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE>",
        "<OUTPUT><PARENTHESIS_OPEN><STRING><WHITESPACE><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE>",
        "<OUTPUT><PARENTHESIS_OPEN><IDENTIFIER><PARENTHESIS_CLOSE>",
        "<OUTPUT><PARENTHESIS_OPEN><STRING><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE>",


        "<INDENT><OUTPUT><PARENTHESIS_OPEN><IDENTIFIER><PARENTHESIS_CLOSE>",
        "<INDENT><OUTPUT><PARENTHESIS_OPEN><STRING><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE>",

        "<INDENT><OUTPUT><PARENTHESIS_OPEN><STRING><PARENTHESIS_CLOSE><WHITESPACE>",
        "<INDENT><OUTPUT><PARENTHESIS_OPEN><IDENTIFIER><PARENTHESIS_CLOSE><WHITESPACE>",
        "<INDENT><OUTPUT><PARENTHESIS_OPEN><STRING><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE><WHITESPACE>"

]

ARITHMETIC_OPERATOR = [
        # int x + int y
        "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><PLUS><WHITESPACE><DT_INT><WHITESPACE><IDENTIFIER>",
        "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><MINUS><WHITESPACE><DT_INT><WHITESPACE><IDENTIFIER>",
        "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><MULTIPLY><WHITESPACE><DT_INT><WHITESPACE><IDENTIFIER>",
        "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><DIVIDE><WHITESPACE><DT_INT><WHITESPACE><IDENTIFIER>",

        # deci x + deci y
        "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><PLUS><WHITESPACE><DT_DECI><WHITESPACE><IDENTIFIER>",
        "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><MINUS><WHITESPACE><DT_DECI><WHITESPACE><IDENTIFIER>",
        "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><MULTIPLY><WHITESPACE><DT_DECI><WHITESPACE><IDENTIFIER>",
        "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><DIVIDE><WHITESPACE><DT_DECI><WHITESPACE><IDENTIFIER>",

        #  char x + char y
        "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><PLUS><WHITESPACE><DT_CHAR><WHITESPACE><IDENTIFIER>",
        "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><MINUS><WHITESPACE><DT_CHAR><WHITESPACE><IDENTIFIER>",
        "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><MULTIPLY><WHITESPACE><DT_CHAR><WHITESPACE><IDENTIFIER>",
        "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><DIVIDE><WHITESPACE><DT_CHAR><WHITESPACE><IDENTIFIER>",

        # str test + str test
        "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><PLUS><WHITESPACE><DT_STR><WHITESPACE><IDENTIFIER>",
        "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><MINUS><WHITESPACE><DT_STR><WHITESPACE><IDENTIFIER>",
        "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><MULTIPLY><WHITESPACE><DT_STR><WHITESPACE><IDENTIFIER>",
        "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><DIVIDE><WHITESPACE><DT_STR><WHITESPACE><IDENTIFIER>"
]


UNARY_OPERATOR = [
        # with data type
        "<DT_INT><WHITESPACE><INCREMENT><WHITESPACE><IDENTIFIER>",
        "<DT_INT><WHITESPACE><DECREMENT><WHITESPACE><IDENTIFIER>",
        "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><INCREMENT>",
        "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><DECREMENT>",

        "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL><WHITESPACE><PLUS><WHITESPACE><INTEGER>",
        "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL><WHITESPACE><MINUS><WHITESPACE><INTEGER>",

        # identifiers without data type
        "<INCREMENT><WHITESPACE><IDENTIFIER>",
        "<DECREMENT><WHITESPACE><IDENTIFIER>",
        "<IDENTIFIER><WHITESPACE><INCREMENT>",
        "<IDENTIFIER><WHITESPACE><DECREMENT>",

        # numbers without data type
        "<INCREMENT><WHITESPACE><INTEGER>",
        "<DECREMENT><WHITESPACE><INTEGER>",
        "<INTEGER><WHITESPACE><INCREMENT>",
        "<INTEGER><WHITESPACE><DECREMENT>",
]

BOOLEAN_LOGIC = [
    # <BOOLEAN_LOGIC> = LOGICAL_NOT | LOGICAL_OR | LOGICAL_AND
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_NOT><WHITESPACE><DT_INT><IDENTIFIER>",
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_OR><WHITESPACE><DT_INT><IDENTIFIER>",
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_AND><WHITESPACE><DT_INT><IDENTIFIER>",

    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_NOT><WHITESPACE><DT_DECI><IDENTIFIER>",
    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_OR><WHITESPACE><DT_DECI><IDENTIFIER>",
    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_AND><WHITESPACE><DT_DECI><IDENTIFIER>",

    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_NOT><WHITESPACE><DT_CHAR><IDENTIFIER>",
    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_OR><WHITESPACE><DT_CHAR><IDENTIFIER>",
    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_AND><WHITESPACE><DT_CHAR><IDENTIFIER>",

    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_NOT><WHITESPACE><DT_STR><IDENTIFIER>",
    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_OR><WHITESPACE><DT_STR><IDENTIFIER>",
    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_AND><WHITESPACE><DT_STR><IDENTIFIER>",

    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_NOT><WHITESPACE><DT_BOOL><IDENTIFIER>",
    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_OR><WHITESPACE><DT_BOOL><IDENTIFIER>",
    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_AND><WHITESPACE><DT_BOOL><IDENTIFIER>",

    # "<DATA_TYPE><WHITESPACE><IDENTIFIER><WHITESPACE><BOOLEAN_LOGIC><WHITESPACE><VALUE>"
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_NOT><WHITESPACE><INTEGER>",
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_OR><WHITESPACE><INTEGER>",
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_AND><WHITESPACE><INTEGER>",

    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_NOT><WHITESPACE><DECIMAL>",
    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_OR><WHITESPACE><DECIMAL>",
    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_AND><WHITESPACE><DECIMAL>",

    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_NOT><WHITESPACE><CHAR>",  # -------------------------
    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_OR><WHITESPACE><CHAR>",  # -------------------------
    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_AND><WHITESPACE><CHAR>",  # -------------------------

    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_NOT><WHITESPACE><STRING>",
    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_OR><WHITESPACE><STRING>",
    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_AND><WHITESPACE><STRING>",

    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_NOT><WHITESPACE><BOOL_VALUE>",
    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_OR><WHITESPACE><BOOL_VALUE>",
    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><LOGICAL_AND><WHITESPACE><BOOL_VALUE>"

    "<BOOL_VALUE><WHITESPACE><LOGICAL_NOT><WHITESPACE><BOOL_VALUE>",
    "<BOOL_VALUE><WHITESPACE><LOGICAL_OR><WHITESPACE><BOOL_VALUE>",
    "<BOOL_VALUE><WHITESPACE><LOGICAL_AND><WHITESPACE><BOOL_VALUE>",
    "BOOL_VALUE"

]

BOOLEAN_RELATION = [  # dapat same ng data type, rules q yan
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL_TO><WHITESPACE><DT_INT><WHITESPACE><IDENTIFIER>",
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><NOT_EQUAL><WHITESPACE><DT_INT><WHITESPACE><IDENTIFIER>",
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><GREATER_THAN><WHITESPACE><DT_INT><WHITESPACE><IDENTIFIER>",
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><LESS_THAN><WHITESPACE><DT_INT><WHITESPACE><IDENTIFIER>",
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><DT_INT><WHITESPACE><IDENTIFIER>",
    "<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><DT_INT><WHITESPACE><IDENTIFIER>",

    # e.g. deci x >= deci y
    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL_TO><WHITESPACE><DT_DECI><WHITESPACE><IDENTIFIER>",
    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><NOT_EQUAL><WHITESPACE><DT_DECI><WHITESPACE><IDENTIFIER>",
    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><GREATER_THAN><WHITESPACE><DT_DECI><WHITESPACE><IDENTIFIER>",
    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><LESS_THAN><WHITESPACE><DT_DECI><WHITESPACE><IDENTIFIER>",
    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><DT_DECI><WHITESPACE><IDENTIFIER>",
    "<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><DT_DECI><WHITESPACE><IDENTIFIER>",

    # e.g. str x <= str x
    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL_TO><WHITESPACE><DT_STR><WHITESPACE><IDENTIFIER>",
    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><NOT_EQUAL><WHITESPACE><DT_STR><WHITESPACE><IDENTIFIER>",
    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><GREATER_THAN><WHITESPACE><DT_STR><WHITESPACE><IDENTIFIER>",
    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><LESS_THAN><WHITESPACE><DT_STR><WHITESPACE><IDENTIFIER>",
    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><DT_STR><WHITESPACE><IDENTIFIER>",
    "<DT_STR><WHITESPACE><IDENTIFIER><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><DT_STR><WHITESPACE><IDENTIFIER>",

    # e.g. char x <= char x
    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL_TO><WHITESPACE><DT_CHAR><WHITESPACE><IDENTIFIER>",
    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><NOT_EQUAL><WHITESPACE><DT_CHAR><WHITESPACE><IDENTIFIER>",
    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><GREATER_THAN><WHITESPACE><DT_CHAR><WHITESPACE><IDENTIFIER>",
    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><LESS_THAN><WHITESPACE><DT_CHAR><WHITESPACE><IDENTIFIER>",
    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><DT_CHAR><WHITESPACE><IDENTIFIER>",
    "<DT_CHAR><WHITESPACE><IDENTIFIER><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><DT_CHAR><WHITESPACE><IDENTIFIER>",

    # e.g. bool x <= bool x
    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL_TO><WHITESPACE><DT_BOOL><WHITESPACE><IDENTIFIER>",
    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><NOT_EQUAL><WHITESPACE><DT_BOOL><WHITESPACE><IDENTIFIER>",
    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><GREATER_THAN><WHITESPACE><DT_BOOL><WHITESPACE><IDENTIFIER>",
    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><LESS_THAN><WHITESPACE><DT_BOOL><WHITESPACE><IDENTIFIER>",
    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><DT_BOOL><WHITESPACE><IDENTIFIER>",
    "<DT_BOOL><WHITESPACE><IDENTIFIER><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><DT_BOOL><WHITESPACE><IDENTIFIER>",

    # e.g. x <= y
    "<IDENTIFIER><WHITESPACE><EQUAL_TO><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><WHITESPACE><NOT_EQUAL><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><WHITESPACE><GREATER_THAN><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><WHITESPACE><LESS_THAN><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><IDENTIFIER>",

    # e.g. x <= 12
    "<IDENTIFIER><WHITESPACE><EQUAL_TO><WHITESPACE><INTEGER>",
    "<IDENTIFIER><WHITESPACE><NOT_EQUAL><WHITESPACE><INTEGER>",
    "<IDENTIFIER><WHITESPACE><GREATER_THAN><WHITESPACE><INTEGER>",
    "<IDENTIFIER><WHITESPACE><LESS_THAN><WHITESPACE><INTEGER>",
    "<IDENTIFIER><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><INTEGER>",
    "<IDENTIFIER><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><INTEGER>",

    # e.g. x <= 12.34
    "<IDENTIFIER><WHITESPACE><EQUAL_TO><WHITESPACE><DECIMAL>",
    "<IDENTIFIER><WHITESPACE><NOT_EQUAL><WHITESPACE><DECIMAL>",
    "<IDENTIFIER><WHITESPACE><GREATER_THAN><WHITESPACE><DECIMAL>",
    "<IDENTIFIER><WHITESPACE><LESS_THAN><WHITESPACE><DECIMAL>",
    "<IDENTIFIER><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><DECIMAL>",
    "<IDENTIFIER><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><DECIMAL>",

    # e.g. x <= "SDASD"
    "<IDENTIFIER><WHITESPACE><EQUAL_TO><WHITESPACE><STRING>",
    "<IDENTIFIER><WHITESPACE><NOT_EQUAL><WHITESPACE><STRING>",
    "<IDENTIFIER><WHITESPACE><GREATER_THAN><WHITESPACE><STRING>",
    "<IDENTIFIER><WHITESPACE><LESS_THAN><WHITESPACE><STRING>",
    "<IDENTIFIER><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><STRING>",
    "<IDENTIFIER><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><STRING>",

    # e.g. x <= 12
    "<IDENTIFIER><WHITESPACE><EQUAL_TO><WHITESPACE><CHAR>",
    "<IDENTIFIER><WHITESPACE><NOT_EQUAL><WHITESPACE><CHAR>",
    "<IDENTIFIER><WHITESPACE><GREATER_THAN><WHITESPACE><CHAR>",
    "<IDENTIFIER><WHITESPACE><LESS_THAN><WHITESPACE><CHAR>",
    "<IDENTIFIER><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><CHAR>",
    "<IDENTIFIER><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><CHAR>",

    # e.g. x <= "SDASD"
    "<IDENTIFIER><WHITESPACE><EQUAL_TO><WHITESPACE><BOOL_VALUE>",
    "<IDENTIFIER><WHITESPACE><NOT_EQUAL><WHITESPACE><BOOL_VALUE>",
    "<IDENTIFIER><WHITESPACE><GREATER_THAN><WHITESPACE><BOOL_VALUE>",
    "<IDENTIFIER><WHITESPACE><LESS_THAN><WHITESPACE><BOOL_VALUE>",
    "<IDENTIFIER><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><BOOL_VALUE>",
    "<IDENTIFIER><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><BOOL_VALUE>",
    
    # e.g. 12 < X
    "<IDENTIFIER><INTEGER><EQUAL_TO><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><INTEGER><NOT_EQUAL><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><INTEGER><GREATER_THAN><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><INTEGER><LESS_THAN><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><INTEGER><GREATER_THAN_EQUAL><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><INTEGER><LESS_THAN_EQUAL><WHITESPACE><IDENTIFIER>",

    # e.g. 12.5 < X
    "<IDENTIFIER><DECIMAL><EQUAL_TO><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><DECIMAL><NOT_EQUAL><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><DECIMAL><GREATER_THAN><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><DECIMAL><LESS_THAN><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><DECIMAL><GREATER_THAN_EQUAL><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><DECIMAL><LESS_THAN_EQUAL><WHITESPACE><IDENTIFIER>",

    # e.g. 12.5 < X
    "<IDENTIFIER><STRING><EQUAL_TO><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><STRING><NOT_EQUAL><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><STRING><GREATER_THAN><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><STRING><LESS_THAN><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><STRING><GREATER_THAN_EQUAL><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><STRING><LESS_THAN_EQUAL><WHITESPACE><IDENTIFIER>",

    # e.g. "SFDFS" < X
    "<IDENTIFIER><CHAR><EQUAL_TO><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><CHAR><NOT_EQUAL><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><CHAR><GREATER_THAN><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><CHAR><LESS_THAN><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><CHAR><GREATER_THAN_EQUAL><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><CHAR><LESS_THAN_EQUAL><WHITESPACE><IDENTIFIER>",

    # e.g. TRUE < X
    "<IDENTIFIER><BOOL_VALUE><EQUAL_TO><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><BOOL_VALUE><NOT_EQUAL><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><BOOL_VALUE><GREATER_THAN><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><BOOL_VALUE><LESS_THAN><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><BOOL_VALUE><GREATER_THAN_EQUAL><WHITESPACE><IDENTIFIER>",
    "<IDENTIFIER><BOOL_VALUE><LESS_THAN_EQUAL><WHITESPACE><IDENTIFIER>",

    # 12 >= 13
    "<INTEGER><WHITESPACE><EQUAL_TO><WHITESPACE><INTEGER>",
    "<INTEGER><WHITESPACE><NOT_EQUAL><WHITESPACE><INTEGER>",
    "<INTEGER><WHITESPACE><GREATER_THAN><WHITESPACE><INTEGER>",
    "<INTEGER><WHITESPACE><LESS_THAN><WHITESPACE><INTEGER>",
    "<INTEGER><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><INTEGER>",
    "<INTEGER><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><INTEGER>",

    # 12.312 <= 12.231
    "<DECIMAL><WHITESPACE><EQUAL_TO><WHITESPACE><DECIMAL>",
    "<DECIMAL><WHITESPACE><NOT_EQUAL><WHITESPACE><DECIMAL>",
    "<DECIMAL><WHITESPACE><GREATER_THAN><WHITESPACE><DECIMAL>",
    "<DECIMAL><WHITESPACE><LESS_THAN><WHITESPACE><DECIMAL>",
    "<DECIMAL><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><DECIMAL>",
    "<DECIMAL><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><DECIMAL>",
    
    # TRUE == FALSE
    "<BOOL_VALUE><WHITESPACE><EQUAL_TO><WHITESPACE><BOOL_VALUE>",
    "<BOOL_VALUE><WHITESPACE><NOT_EQUAL><WHITESPACE><BOOL_VALUE>",
    "<BOOL_VALUE><WHITESPACE><GREATER_THAN><WHITESPACE><BOOL_VALUE>",
    "<BOOL_VALUE><WHITESPACE><LESS_THAN><WHITESPACE><BOOL_VALUE>",
    "<BOOL_VALUE><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><BOOL_VALUE>",
    "<BOOL_VALUE><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><BOOL_VALUE>",

    # "TEST" >= "TASTY"
    "<STRING><WHITESPACE><EQUAL_TO><WHITESPACE><STRING>",
    "<STRING><WHITESPACE><NOT_EQUAL><WHITESPACE><STRING>",
    "<STRING><WHITESPACE><GREATER_THAN><WHITESPACE><STRING>",
    "<STRING><WHITESPACE><LESS_THAN><WHITESPACE><STRING>",
    "<STRING><WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE><STRING>",
    "<STRING><WHITESPACE><LESS_THAN_EQUAL><WHITESPACE><STRING>",

]
for x in BOOLEAN_RELATION:
        for y in BOOLEAN_RELATION:
                BOOLEAN_LOGIC.append(f"{x}<WHITESPACE><LOGICAL_NOT><WHITESPACE>{y}")
                BOOLEAN_LOGIC.append(f"{x}<WHITESPACE><LOGICAL_OR><WHITESPACE>{y}")
                BOOLEAN_LOGIC.append(f"{x}<WHITESPACE><LOGICAL_AND><WHITESPACE>{y}")

# e.g. x + y == x - y
for x in ARITHMETIC_OPERATOR:
        for y in ARITHMETIC_OPERATOR:
                BOOLEAN_RELATION.append(f"{x}<WHITESPACE><EQUAL_TO><WHITESPACE>{y}")
                BOOLEAN_RELATION.append(f"{x}<WHITESPACE><NOT_EQUAL><WHITESPACE>{y}")
                BOOLEAN_RELATION.append(f"{x}<WHITESPACE><GREATER_THAN><WHITESPACE>{y}")
                BOOLEAN_RELATION.append(f"{x}<WHITESPACE><LESS_THAN><WHITESPACE>{y}")
                BOOLEAN_RELATION.append(f"{x}<WHITESPACE><GREATER_THAN_EQUAL><WHITESPACE>{y}")
                BOOLEAN_RELATION.append(f"{x}<WHITESPACE><LESS_THAN_EQUAL><WHITESPACE>{y}")


CONDITIONAL_STMT = [
    "<OTHERWISE><COLON_DELIMITER>",
    "<OTHERWISE><COLON_DELIMITER><WHITESPACE>",
    "<INVALID_TOKEN><OTHERWISE><COLON_DELIMITER>",
    "<INVALID_TOKEN><OTHERWISE><COLON_DELIMITER><WHITESPACE>"
]

NEW_PRINCIPLES = [
"<ARITHSEQ><PARENTHESIS_OPEN><INTEGER><COMMA><WHITESPACE><INTEGER><COMMA><WHITESPACE><INTEGER><PARENTHESIS_CLOSE>",
"<ARITHSEQ><PARENTHESIS_OPEN><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE>",

"<ARITHSER><PARENTHESIS_OPEN><INTEGER><COMMA><WHITESPACE><INTEGER><COMMA><WHITESPACE><INTEGER><PARENTHESIS_CLOSE>", 
"<ARITHSER><PARENTHESIS_OPEN><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE>",

"<GEOSEQ><PARENTHESIS_OPEN><INTEGER><COMMA><WHITESPACE><INTEGER><COMMA><WHITESPACE><INTEGER><PARENTHESIS_CLOSE>", 
"<GEOSEQ><PARENTHESIS_OPEN><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE>",

"<GEOSER><PARENTHESIS_OPEN><INTEGER><COMMA><WHITESPACE> <INTEGER><COMMA> <WHITESPACE><INTEGER><PARENTHESIS_CLOSE>", 
"<GEOSER><PARENTHESIS_OPEN><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE>",

"<DISTANCE><PARENTHESIS_OPEN><INTEGER><COMMA><WHITESPACE><INTEGER><COMMA><WHITESPACE><INTEGER><COMMA><WHITESPACE><INTEGER><PARENTHESIS_CLOSE>", 
"<DISTANCE><PARENTHESIS_OPEN><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE>",

"<SLOPE><PARENTHESIS_OPEN><INTEGER><COMMA><WHITESPACE><INTEGER><COMMA><WHITESPACE><INTEGER><PARENTHESIS_CLOSE>", 
"<SLOPE><PARENTHESIS_OPEN><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE>",

"<PYTHAGOREAN><PARENTHESIS_OPEN><INTEGER><COMMA><WHITESPACE><INTEGER><PARENTHESIS_CLOSE>", 
"<PYTHAGOREAN><PARENTHESIS_OPEN><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE>",

"<QUADRATIC><PARENTHESIS_OPEN><INTEGER><COMMA><WHITESPACE><INTEGER><COMMA><WHITESPACE><INTEGER><PARENTHESIS_CLOSE>", 
"<QUADRATIC><PARENTHESIS_OPEN><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE>",

"<FORCE><PARENTHESIS_OPEN><INTEGER><COMMA><WHITESPACE><INTEGER><PARENTHESIS_CLOSE>", 
"<FORCE><PARENTHESIS_OPEN><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE>",

"<WORK><PARENTHESIS_OPEN><INTEGER><COMMA><WHITESPACE><INTEGER><PARENTHESIS_CLOSE>", 
"<WORK><PARENTHESIS_OPEN><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE>",

"<ACCELERATION><PARENTHESIS_OPEN><INTEGER><COMMA><WHITESPACE><INTEGER><COMMA><WHITESPACE><INTEGER><COMMA><WHITESPACE><INTEGER><PARENTHESIS_CLOSE>", 
"<ACCELERATION><PARENTHESIS_OPEN><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE>",

"<POWER><PARENTHESIS_OPEN><INTEGER><COMMA><WHITESPACE><INTEGER><PARENTHESIS_CLOSE>", 
"<POWER><PARENTHESIS_OPEN><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE>",

"<MOMENTUM><PARENTHESIS_OPEN><INTEGER><COMMA><WHITESPACE><INTEGER><PARENTHESIS_CLOSE>", 
"<MOMENTUM><PARENTHESIS_OPEN><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE>",

"<POTENTIAL><PARENTHESIS_OPEN><INTEGER><COMMA><WHITESPACE><INTEGER><PARENTHESIS_CLOSE>", 
"<POTENTIAL><PARENTHESIS_OPEN><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE>",

"<KINETIC><PARENTHESIS_OPEN><INTEGER><COMMA><WHITESPACE><INTEGER><PARENTHESIS_CLOSE>", 
"<KINETIC><PARENTHESIS_OPEN><IDENTIFIER><COMMA><WHITESPACE><IDENTIFIER><PARENTHESIS_CLOSE>",

"<TOINT><PARENTHESIS_OPEN><DIGIT><WHITESPACE>+<WHITESPACE><INTEGER><PARENTHESIS_CLOSE>", 
"<TOINT><PARENTHESIS_OPEN><DIGIT><PARENTHESIS_CLOSE>",
"<TOINT><PARENTHESIS_OPEN><IDENTIFIER><PARENTHESIS_CLOSE>",

"<TODECI><PARENTHESIS_OPEN><INTEGER><PARENTHESIS_CLOSE>",
"<TODECI><PARENTHESIS_OPEN><IDENTIFIER><PARENTHESIS_CLOSE>",

"<TOSTR><PARENTHESIS_OPEN><INTEGER><PARENTHESIS_CLOSE>",
"<TOSTR><PARENTHESIS_OPEN><DECIMAL><PARENTHESIS_CLOSE>",
"<TOSTR><PARENTHESIS_OPEN><IDENTIFIER><PARENTHESIS_CLOSE>"
]

# assigning new principles to variables
for principle in NEW_PRINCIPLES:
    ASSIGNMENT_STMT.append(f"<DT_INT><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL><WHITESPACE>{principle}")
    ASSIGNMENT_STMT.append(f"<DT_DECI><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL><WHITESPACE>{principle}")
    OUTPUT_STMT.append(f"<OUTPUT><PARENTHESIS_OPEN>{principle}<PARENTHESIS_CLOSE>")

for condition in BOOLEAN_RELATION:
    CONDITIONAL_STMT.append(f"<WHEN><PARENTHESIS_OPEN>{condition}<PARENTHESIS_CLOSE><COLON_DELIMITER>")
    CONDITIONAL_STMT.append(f"<OTHERWISE><WHITESPACE><WHEN><PARENTHESIS_OPEN>{condition}<PARENTHESIS_CLOSE><COLON_DELIMITER>")

for condition in BOOLEAN_LOGIC:
    CONDITIONAL_STMT.append(f"<WHEN><PARENTHESIS_OPEN>{condition}<PARENTHESIS_CLOSE><COLON_DELIMITER>")
    CONDITIONAL_STMT.append(f"<OTHERWISE><WHITESPACE><WHEN><PARENTHESIS_OPEN>{condition}<PARENTHESIS_CLOSE><COLON_DELIMITER>")


ITERATIVE_STMT = [
    # e.g. loop i = 1 to 10 (i ++):
    "<LOOP><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL><WHITESPACE><INTEGER><WHITESPACE><TO><WHITESPACE><INTEGER><WHITESPACE><PARENTHESIS_OPEN><IDENTIFIER><WHITESPACE><INCREMENT><PARENTHESIS_CLOSE><COLON_DELIMITER>",
    "<LOOP><WHITESPACE><IDENTIFIER><WHITESPACE><EQUAL><WHITESPACE><INTEGER><WHITESPACE><TO><WHITESPACE><INTEGER><WHITESPACE><PARENTHESIS_OPEN><IDENTIFIER><WHITESPACE><DECREMENT><PARENTHESIS_CLOSE><COLON_DELIMITER>"
]

BODY_STMT = []
COMMENT_STMT = [
    "<COMMENT_MULTI>",
    "<COMMENT_SYM_MULTI><COMMENT_MULTI><CHAR_COMMENT_SYM_MULTI>",
    "<CHAR_COMMENT_SYM_SINGLE><COMMENT_SINGLE>"
]

STATEMENTS_LIST = [DECLARATION_STMT, ASSIGNMENT_STMT, INPUT_STMT, OUTPUT_STMT, ARITHMETIC_OPERATOR, UNARY_OPERATOR, BOOLEAN_LOGIC,
                   BOOLEAN_RELATION, CONDITIONAL_STMT, NEW_PRINCIPLES, ITERATIVE_STMT, BODY_STMT]
combined_list = sum(STATEMENTS_LIST, [])

# accept indented
for x in combined_list:
    indented = f"<WHITESPACE><WHITESPACE><WHITESPACE><WHITESPACE><WHITESPACE><WHITESPACE><WHITESPACE><WHITESPACE>{x}"
    BODY_STMT.append(indented)

    indented = f"<WHITESPACE><INDENT>{x}"
    BODY_STMT.append(indented)

    indented = f"<INDENT>{x}"
    BODY_STMT.append(indented)

    indented = f"<INDENT2>{x}"
    BODY_STMT.append(indented)

    indented = f"<INDENT><INDENT>{x}"
    BODY_STMT.append(indented)

    indented = f"<INDENT2><INDENT2>{x}"
    BODY_STMT.append(indented)

    indented = f"<INDENT><INDENT><INDENT>{x}"
    BODY_STMT.append(indented)

    indented = f"<INDENT2><INDENT2><INDENT2>{x}"
    BODY_STMT.append(indented)

# handle line of codes that have whitespace/indent in the end of line
for x in combined_list:
    excess_space = f"{x}<INDENT>"
    BODY_STMT.append(excess_space)

    excess_space = f"{x}<WHITESPACE>"
    BODY_STMT.append(excess_space)

    excess_space = f"<WHITESPACE><WHITESPACE>{x}"
    BODY_STMT.append(excess_space)

    excess_space = f"<WHITESPACE><WHITESPACE><WHITESPACE>{x}"
    BODY_STMT.append(excess_space)

for x in combined_list:
    comment_s = f"{x}<WHITESPACE><CHAR_COMMENT_SYM_SINGLE><COMMENT_SINGLE>"
    comment_m = f"{x}<WHITESPACE><CHAR_COMMENT_SYM_MULTI><COMMENT_MULTI>"
    COMMENT_STMT.append(comment_s)
    COMMENT_STMT.append(comment_m)

STATEMENTS_LIST = [DECLARATION_STMT, MULTI_DECLARATION_STMT, ASSIGNMENT_STMT, INPUT_STMT, OUTPUT_STMT, ARITHMETIC_OPERATOR, UNARY_OPERATOR, BOOLEAN_LOGIC,
                   BOOLEAN_RELATION, CONDITIONAL_STMT, NEW_PRINCIPLES, ITERATIVE_STMT, BODY_STMT, COMMENT_STMT]
